//v8 © 2010 Tynt
var Tynt=Tynt||[];
if(typeof Tynt.TIL=="undefined"){(function(){var za=function(){var i=document,k=i.body,o=i.documentElement,W=eval("/*@cc_on!@*/false"),y="w."+(Tynt.e||"")+"ic.tynt.com",ga="p."+(Tynt.e||"")+"ic.tynt.com",X=function(a,b){for(var c="",f=0;f<b;f++)c+=a;return c},z=X("a",50),D=function(a){return a.replace(/^\s+|\s+$/g,"")},x=function(a,b,c){a=i.createElement(a);for(var f in b)if(b.hasOwnProperty(f))a[f]=b[f];for(var d in c)if(c.hasOwnProperty(d))a.style[d]=c[d];return a},M,E;if(window.addEventListener){M=function(a,
b,c){a.addEventListener(b,c,false)};E=function(a,b,c){a.removeEventListener(b,c,false)}}else{M=function(a,b,c){a.attachEvent("on"+b,c)};E=function(a,b,c){a.detachEvent("on"+b,c)}}var F=function(a,b){var c=window.location.hostname.split("."),f=2;do{var d=c.slice(c.length-f,c.length).join(".");i.cookie=a+";path=/;domain=."+d+";"+b;f++}while(i.cookie.indexOf(a)==-1&&f<=c.length);if(i.cookie.indexOf(a)==-1)i.cookie=a+";path=/;"+b},n=function(a,b){var c=[],f=function(e,g){c.push([e,g])},d=function(e,g){var l=
x("img",{width:0,height:0,src:"http://"+e.replace("id="+z,"id="+Tynt.join("~"))},{position:"absolute",top:"0"});if(window.addEventListener){l.addEventListener("load",function(j){j.target.parentNode.removeChild(j.target)},false);l.addEventListener("error",function(j){g&&g();j.target.parentNode.removeChild(j.target)},false)}else{l.attachEvent("onload",function(j){j.srcElement.parentNode.removeChild(j.srcElement)});l.attachEvent("onerror",function(j){g&&g();j.srcElement.parentNode.removeChild(j.srcElement)})}k.insertBefore(l,
k.firstChild)};if(i.readyState=="complete")n=d;else{n=f;M(window,"load",function(){setTimeout(function(){if(typeof i.readyState=="undefined"&&!W)i.readyState="complete";n=d;for(var e=0;e<c.length;e++)n(c[e][0],c[e][1]);c=null},10)})}n(a,b)},Y=function(a){var b=[],c="";for(var f in a){b.push(c,f,"=",a[f]);c="&"}return b.join("")},N=function(a){for(var b=0,c=a.length<100?a.length:100,f=0;f<c;f++)b+=a.charCodeAt(f);a=Math.floor(Math.random()*3844);c=Math.abs((new Date).getTime()-12281184E5);return Z(c,
7)+Z((b+a)%3844,2)},$=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?$(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},Z=function(a,b){var c=$(a);return X("0",b-c.length)+c},aa=function(a){return(a=D(a))?a.split(/\s+/i).length:
0},O=D((i.title||window.location.hostname).toString()).replace(RegExp(window.location.hash,"g"),""),ha=function(){for(var a=i.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")){a=a[b].getAttribute("href");b=window.location.protocol+"//"+window.location.host+window.location.pathname;var c=i.getElementsByTagName("base")[0];if(c)b=c.getAttribute("href");if(!a.match(/^http/)){b=a.charAt(0)!="/"?b.slice(0,b.lastIndexOf("/")+1):b.slice(0,
b.indexOf("/",9));a=b+a}return a}return""},G=function(a){return a.replace(/^https?:\/\//,"")},P=function(a,b){for(var c=b+"=",f=a.split(";"),d=0;d<f.length;d++){for(var e=f[d];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c)==0)return e.substring(c.length,e.length)}return null};E=function(){var a=new Date;a.setTime(a.getTime()+12E4);F("tracerurl="+window.location.href,"expires="+a.toUTCString())};var ia=function(){var a=P(i.cookie,"tracertraffic"),b=encodeURIComponent(G(ha())),c=i.location.hash;
c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var f=ga+"/b/p?id="+z+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+(new Date).getTime(),d=f+(b?"&cu="+b:""),e=d+(i.referrer?"&r="+encodeURIComponent(G(i.referrer)):"");a=e+"&t="+encodeURIComponent(O);n(a,function(){n(e,function(){n(d,function(){n(f)})})})},A=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},ja=A(),ka=A(),la=function(){var a,b=function(){window.removeEventListener("blur",
b,false);Q(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",b,false);window.setTimeout(function(){i.removeEventListener("blur",b,false)},1E4)}return true}}(),ba=function(a){Q(a.target||a.srcElement)},H=null,ca=function(a){a=a.target||a.srcElement;H=a.nodeName=="IMG"?a:null},R=function(){var a=function(g){return{x:typeof g.pageX=="number"?g.pageX-(o.scrollLeft?o.scrollLeft:
k.scrollLeft):g.clientX,y:typeof g.pageY=="number"?g.pageY-(o.scrollTop?o.scrollTop:k.scrollTop):g.clientY}},b=function(g){g=a(g);return g.x<=0||g.y<=0||g.x>=k.clientWidth||g.y>=k.clientHeight},c=function(g){g=a(g);return g.x<=0||g.y<=0||g.x>=o.clientWidth||g.y>=o.clientHeight},f=function(g){return g.target.nodeName=="#document"},d=function(g){g=a(g);return g.x<=4||g.y<=4||g.x>=o.clientWidth-4||g.y>=o.clientHeight-4},e=function(g){e=window.navigator.userAgent.match("MSIE")?!i.compatMode||i.compatMode.indexOf("CSS")==
-1?b:c:window.navigator.userAgent.match("Firefox")?f:d;e(g)};return function(g){if(H&&e(g)){Q(H);H=null}return true}}(),t;if(Tynt.c)t=function(){};else{Tynt.c=true;t=function(){var a=true,b,c=function(f,d){var e={id:z,wc:aa(d),c:d,f:a?1:0,t:O};for(var g in f)if(f.hasOwnProperty(g))e[g]=f[g];a=false;g=e.trace_type;delete e.trace_type;var l=e.g;delete e.g;for(var j=[],p=["id","wc","f","w","h","t","c"],m=0;m<p.length;m++){var q=p[m],r=e[q];r&&j.push([q,encodeURIComponent(r).replace(/\'/g,"%27")]);delete e[q]}for(var u in e)if(e.hasOwnProperty(u))(p=
e[u])&&j.push([u,encodeURIComponent(p).replace(/\'/g,"%27")]);e=[];u=2048-(("http://"+y+"/a/t/x#?").length+(3+l.length)+5);p=j.length;m=0;var v,I,S,J,s=q=r=0;for(e[s]={g:l,tp:null};m<p;){v=j[m][0];S=v.length+2;I=u-S-q;if(I>0){e[s][v]=j[m][1].substring(r,r+I);J=e[s][v].slice(-2).indexOf("%");if(J>-1){e[s][v]=j[m][1].substring(r,r+I-2+J);q+=J+2}q+=e[s][v].length+S;r+=e[s][v].length}else q=u;if(q>=u){e[++s]={g:l,p:s};q=0}if(r>=j[m][1].length){m++;r=0}}e[0].tp=e.length;n(y+"/b/t/"+g+"?"+Y(e[0]));for(l=
1;l<e.length;l++)n(y+"/b/x/"+g+"?"+Y(e[l]))};if(window.addEventListener){window.navigator.userAgent.match("Firefox/2")||k.addEventListener("copy",ba,false);window.addEventListener("mousedown",ca,false);window.addEventListener("dragleave",R,false);window.addEventListener("dragexit",R,false);i.addEventListener("contextmenu",la,false)}else{k.attachEvent("oncopy",ba);i.getElementsByTagName("html")[0].attachEvent("ondragleave",R);k.attachEvent("onmousedown",ca)}if(i.cookie.indexOf("tracertraffic=")!=-1)if(!i.referrer||
i.referrer.indexOf(window.location.host)==-1)F("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");ia();return function(f){var d;d=f.src;if(!i.getElementById("tyntSS"))if(d){if(ka(d)){d=d;c({g:N(d),trace_type:3,w:f.width,h:f.height},d)}}else{d=typeof window.getSelection!="undefined"?window.getSelection().toString():i.selection.createRange().text;if(!(!D(d).length||f.nodeName=="TEXTAREA"||f.nodeName=="INPUT")){f=ja(d);var e={trace_type:1};if(f)b=N(d);e.g=b;var g=Tynt.m?Tynt.m(e,d):true;f&&g&&
c(e,d)}}}}}var K=function(a){a=a.charCodeAt(0);return 3584<=a&&a<=3711||11904<=a&&a<=12591||12688<=a&&a<=40959||63744<=a&&a<=64255||65072<=a&&a<=65103||131072<=a&&a<=173791||194560<=a&&a<=195103},ma=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;b--){var c=a[b];c.parentNode.removeChild(c)}},h,na="r."+(Tynt.e||"")+"id.tynt.com",oa={t:3,p:6,w:7},w,T,U,pa=["","Attribution","Attribution Share Alike","Attribution No Derivatives","Attribution Non-Commercial","Attribution Non-Commercial Share Alike",
"Attribution Non-Commercial No Derivatives"],qa=["","http://creativecommons.org/licenses/by/3.0","http://creativecommons.org/licenses/by-sa/3.0","http://creativecommons.org/licenses/by-nd/3.0","http://creativecommons.org/licenses/by-nc/3.0","http://creativecommons.org/licenses/by-nc-sa/3.0","http://creativecommons.org/licenses/by-nc-nd/3.0"],da=function(a){a=a.match(/ixzz=?([^?$#]*)/);if(!a)return null;a=a[1].match(/&([^?$]*)/);if(Tynt.k)return Tynt.k.charAt(1);if(!a||!a[1])return null;return a[1]},
V=function(a){return(a=a.match(/axzz([^?$]*)/))&&a.length==2?a[1]:null},ra=function(a){var b=window.location.href;b=b.replace(/#(i|a)xzz=?(.*)$/g,"");return b+"#"+("ixzz"+a)};A=function(a){var b=new Date;b.setTime(b.getTime()+864E5);F("tracertraffic="+a.toString(),"expires="+b.toUTCString())};var sa=function(){var a=window.location.href.match(/ixzz=?([^?&$#]*)/);if(a=(a&&a.length==2?a[1]:null)||Tynt.h){var b=da(window.location.href);a=y+"/b/v?g="+a+(/\?trace_owner_view/.test(window.location.href)?
"&o=y":"")+"&id="+z+(b?"&s="+b:"")+"&r="+encodeURIComponent(G(i.referrer))+"&ts="+(new Date).getTime();n(a);return true}return false},ta=function(a){n(y+"/b/a?g="+a+"&id="+z+"&r="+encodeURIComponent(G(i.referrer))+"&ts="+(new Date).getTime(),function(){})},ea=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},B=false,ua=function(a){if(B)return false;B=true;var b="";if(h.a){var c=ra(a),f='<a style="color: #003399;" href="';b+=h.ap;if(h.st)b=b+f+c+'">'+ea(O)+"</a> ";
if(h.su)b=b+f+c+'">'+ea(c)+"</a>";if(h.as.length>0)b=b+"\n<br>"+h.as+" ";if(h.cc>0)b=b+"\n<br>Under Creative Commons License: "+f+qa[h.cc]+'">'+pa[h.cc]+"</a>"}if(h.el){if(b.length>0)b+="\n<br>";b+=h.el}if(w){if(b.length>0)b+="\n<br>";b=U?b+T+f+"http://tcr"+h.s+".tynt.com/ads/"+U+"/"+a+'">'+w+"</a>":b+T+f+"http://tcr"+h.s+".tynt.com/ads/"+w+"/"+C+"/"+a+'">'+w+"</a>"}var d,e;d=x("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"transparent",textAlign:"left",textDecoration:"none",border:"none"});
if(typeof window.getSelection!="undefined"){var g=window.getSelection();if(g.toString()){var l=g.getRangeAt(0);a=x("span",{innerHTML:b});if(h.t){a.innerHTML+="<br/><br/>";d.appendChild(a);d.appendChild(l.cloneContents())}else{d.appendChild(l.cloneContents());a.innerHTML="<br/><br/>"+a.innerHTML;d.appendChild(a)}ma(d);if(typeof g.setBaseAndExtent!="undefined"){d.style.width=0.1;d.style.height=0.1;d.style.position="absolute";d.style.top="-1000px";d.style.left="-1001px";d.appendChild(i.createElement("br"));
a=d.innerText.length;k.insertBefore(d,k.firstChild);if(d.innerText.length!=a)d.style.overflow="";g.selectAllChildren(d);window.setTimeout(function(){d.parentNode.removeChild(d);window.getSelection().setBaseAndExtent(l.startContainer,l.startOffset,l.endContainer,l.endOffset);B=false},0)}else{e=x("div");k.appendChild(e);e.appendChild(d);a=i.createRange();a.selectNode(d);g.removeAllRanges();g.addRange(a);window.setTimeout(function(){e.parentNode.removeChild(e);g.removeAllRanges();g.addRange(l);B=false},
0)}}}else{var j=o.scrollLeft||k.scrollLeft,p=o.scrollTop||k.scrollTop;e=x("div",{},{visibility:"hidden",overflow:"hidden",position:"absolute",left:j+20+"px",top:p+20+"px",width:"1px",height:"1px"});k.insertBefore(e,k.firstChild);var m=i.selection.createRange();d.innerHTML=h.t?b+"<br><br>"+m.htmlText:m.htmlText+"<br><br>"+b;e.appendChild(i.createElement("br"));e.appendChild(d);a=k.createTextRange();a.moveToElementText(d);a.select();window.setTimeout(function(){e.parentNode.removeChild(e);if(m.text!=
""){m.select();o.scrollLeft=j;k.scrollLeft=j;o.scrollTop=p;k.scrollTop=p}B=false},0)}return true},va=function(a,b){var c=true;if(h.a||w||h.el){var f;f=D(b);if((f=f.length>=2?K(f.charAt(0))||K(f.charAt(f.length-1))||K(f.charAt(f.length/2)):K(f))&&b.length>14||!f&&aa(b)>7)if(h.a||w||h.el){c=ua(a.g);if(h.a)a.trace_type=0}}return c},wa=function(){for(var a=i.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/show_afs_search\.js/i.test(a[b].src))return true;return false},xa=function(a){h=Tynt.i||
window.tyntVariables||{};h.s=a.s||1;h.a=!(h.a==0||a.a==0);h.cc=h.cc||a.cc||0;if(h.cc>6)h.cc=0;h.b=!!(h.b||a.b);if(h.a){h.ap=(h.ap||(typeof tyntAP!="undefined"?tyntAP:null)||"Read more:")+" ";h.as=h.as||(typeof tyntAS!="undefined"?tyntAS:null)||"";h.st=!!(h.st||a.st);h.su=!(h.su==0||a.su==0);h.sp=h.sp||a.sp;if(h.sp){U=h.spid;T=(h.spt||decodeURIComponent(a.spt||""))+" ";w=h.sp||decodeURIComponent(a.sp||"")}}},fa=function(){var a=i.title.indexOf("#ixzz");if(a>-1)i.title=i.title.substring(0,a);a=i.title.indexOf("#axzz");
if(a>-1)i.title=i.title.substring(0,a)},ya=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&Tynt[a].length==22)return Tynt[a];return null},L=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),f=0;f<c.length;f++){var d=c[f].split("=");if(d[0].indexOf("amp;")==0)d[0]=d[0].substring(4);b[d[0]]=d[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=i.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;
return null}()),C=L.user||ya();if(!C)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");L.user&&Tynt.push(L.user);if(!function(){var a=/tracer=test/.test(window.location.href);a&&n(na+"/script/verify/"+C);if(a)return true;if(/tracer=no_tracing/.test(window.location.href))return true;if(/disableTracer=/.test(window.location.href)){a=window.location.href.match(/disableTracer=([^?$]*)/)[1];var b=new Date;b.setDate(a&&a=="on"?b.getDate()+365:b.getDate()-2);F("disableTracer="+
C+";expires="+b.toUTCString());b=x("div",{},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+(a&&a=="on"?"off":"on")+" in this browser.<br>You may close this window.";k.insertBefore(b,k.firstChild);return true}if((a=P(i.cookie,"disableTracer"))&&a==C)return true;return false}()){if(W){fa();i.attachEvent("onpropertychange",
fa)}xa(L);var Q=t();t=oa[da(window.location.href)];if(sa()){t||(t=/tynt.com/.test(i.referrer)?3:1);A(t)}Tynt.m=va;if(h.b){if(V=V(window.location.href)){if(P(i.cookie,"tracerurl")!=window.location.href){ta(V);A(2)}}else if(!wa())if(window.location.hash=="")window.location.hash="axzz"+N(window.location.href);E()}}};Tynt.TIL=function(){document.body?za():window.setTimeout(Tynt.TIL,300)}})();Tynt.TIL()};
