######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 26 16:17:10 2010
######################################################################

TEMPLATE = app
TARGET = 
QT += core \
    gui \
    xml \
    network \
    webkit

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += horoscope.h
SOURCES += horoscope.cpp main.cpp


