######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 23 12:12:34 2010
######################################################################

TEMPLATE = lib
CONFIG  += dll
TARGET = rssparser
DEPENDPATH += .
INCLUDEPATH += .
QT      += core xmlpatterns

# Input
HEADERS += rssparser.h
SOURCES += rssparser.cpp

DESTDIR = c:/mylibs
